name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.10.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.0
  image_picker: 0.8.7+4
  firebase_storage: ^11.1.0
  convex_bottom_bar: 3.2.0
  intl: 0.17.0
  geolocator: 9.0.2
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: 19.4.56
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_localizations: 
  sdk: flutter
  intl_translation: ^0.17.7

flutter_icons:
  android: true
  image_path: "assets/images/images.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/images.jpeg"

flutter: 
  assets: 
    - assets/images/images.jpeg
  uses-material-design: true

